import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { loadPiRuntime } from '../../test-support/pi-runtime.mjs';
const { jiti, buildContextEntries } = await loadPiRuntime(import.meta.url);
const { searchSessions, compileQuery } = await jiti.import('../index.ts');
const temp = await mkdtemp(join(tmpdir(), 'pi-session-search-test-'));
const root = join(temp, 'sessions'), project = join(temp, 'project'), other = join(temp, 'other');
await Promise.all([mkdir(root), mkdir(project), mkdir(other)]);
execFileSync('git', ['init', '-q', project]);
await mkdir(join(project, 'package'));
const timestamp = n => new Date(Date.UTC(2026, 0, 1, 0, n)).toISOString();
const msg = (id, parentId, text, n = 0, role = 'user') => ({ type: 'message', id, parentId, timestamp: timestamp(n), message: { role, content: [{ type: 'text', text }] } });
async function fixture(id, cwd, entries, suffix = '') {
  const file = join(root, `${id}.jsonl`);
  await writeFile(file, [JSON.stringify({ type: 'session', version: 3, id, cwd, timestamp: timestamp(0) }), ...entries.map(e => JSON.stringify(e))].join('\n') + '\n' + suffix);
  return file;
}
const currentEntries = [msg('old', null, 'needle compressed'), msg('kept', 'old', 'needle retained', 1), msg('abandoned', 'old', 'needle abandoned', 2), { type: 'compaction', id: 'compact', parentId: 'kept', timestamp: timestamp(3), firstKeptEntryId: 'kept', summary: 'summary' }, msg('live', 'compact', 'needle live', 4)];
const currentFile = await fixture('current', project, currentEntries);
const ctx = { cwd: project, sessionManager: {
  getSessionId: () => 'current', getSessionFile: () => currentFile,
  getLeafId: () => 'live', getEntries: () => currentEntries,
  buildContextEntries: () => buildContextEntries(currentEntries, 'live'),
} };
const run = params => searchSessions(params, ctx, undefined, root);
const long = Array.from({ length: 40 }, (_, n) => msg(`m${n}`, n ? `m${n - 1}` : null, n === 22 ? `${'x'.repeat(6000)} needle target ${'z'.repeat(6000)}` : n === 0 ? 'b'.repeat(2000) : `message ${n}`, n, n % 2 ? 'assistant' : 'user'));
await fixture('history', join(project, 'package'), long, '{"partial":');
await fixture('external', other, [msg('external-hit', null, 'needle external')]);
await fixture('tools', project, [msg('tool-hit', null, 'unique-tool-error', 0, 'toolResult')]);
await fixture('forks', project, [msg('base', null, 'base'), msg('fork-a', 'base', 'fork A'), msg('fork-a2', 'fork-a', 'fork A next'), msg('fork-b', 'base', 'fork B')]);
assert(compileQuery('foo OR bar AND NOT baz')('foo baz').yes);
assert(!compileQuery('foo OR bar AND NOT baz')('bar baz').yes);
assert(compileQuery('"中文 短语" AND con*')('中文 短语 context').yes);
assert(!compileQuery('con*')('decontext').yes);
assert(compileQuery('a.b')('a.b').yes);
assert(!compileQuery('a.b')('axb').yes);
for (const query of ['foo AND', 'OR foo', '"unterminated', '*', 'foo OR OR bar']) assert.throws(() => compileQuery(query));
const found = await run({ query: 'needle' });
assert.equal(found.mode, 'discover');
assert.equal(found.results.length, 2);
assert.equal(found.detail, 'adaptive');
const historyHit = found.results.find(r => r.session_id === 'history');
const currentHit = found.results.find(r => r.session_id === 'current');
assert.equal(historyHit.detail, 'full');
assert.equal(currentHit.detail, 'compact');
assert.equal(currentHit.messages.length, 1);
const bookend = historyHit.messages.find(m => m.entry_id === 'm0');
assert(bookend.truncated && bookend.text.length === 1200);
assert((await run({ query: 'needle', detail: 'full' })).results.every(r => r.detail === 'full'));
assert(found.warnings.some(w => w.code === 'malformed_jsonl_line'));
assert(!JSON.stringify(found).includes('needle retained'));
assert(!JSON.stringify(found).includes('needle live'));
assert(!JSON.stringify(found).includes('.jsonl'));
assert.equal((await run({ query: 'needle', scope: 'all' })).results.length, 3);
await assert.rejects(run({ session_id: 'external' }), /scope/);
assert.equal((await run({ session_id: 'external', scope: 'all' })).messages.length, 1);
assert.equal((await run({ query: 'unique-tool-error' })).results.length, 0);
assert.equal((await run({ query: 'unique-tool-error', roles: ['toolResult'] })).results.length, 1);
const read = await run({ session_id: 'history' });
assert.equal(read.messages.length, 30); assert.equal(read.omitted_messages, 10);
assert.equal(read.messages[19].entry_id, 'm19'); assert.equal(read.messages[20].entry_id, 'm30');
const scroll = await run({ session_id: 'history', around_entry_id: 'm22' });
assert.equal(scroll.messages.length, 11);
assert.equal((await run({ session_id: 'history', around_entry_id: 'm22', window: 20 })).messages.length, 20);
assert.equal((await run({ session_id: 'history', around_entry_id: 'm22', window: 0 })).messages.length, 1);
const target = await run({ query: 'target' });
const hit = target.results[0].messages.find(m => m.entry_id === 'm22');
assert(hit.truncated && hit.text.includes('target') && hit.text.length === 4000 && hit.offset > 0);
assert.deepEqual((await run({ session_id: 'current' })).messages.map(m => m.entry_id), ['old']);
const abandoned = await run({ session_id: 'current', around_entry_id: 'abandoned' });
assert.equal(abandoned.branch, 'abandoned');
assert.deepEqual(abandoned.messages.map(m => m.entry_id), ['old', 'abandoned']);
await assert.rejects(run({ session_id: 'current', around_entry_id: 'live' }), /accessible/);
assert.deepEqual((await run({ session_id: 'forks' })).messages.map(m => m.entry_id), ['base', 'fork-b']);
assert.deepEqual((await run({ session_id: 'forks', around_entry_id: 'fork-a' })).messages.map(m => m.entry_id), ['base', 'fork-a', 'fork-a2']);
assert.equal((await run({ query: 'needle', after: timestamp(20) })).results.length, 1);
assert(!(await run({ before: timestamp(20) })).results.some(s => s.session_id === 'history'));
assert.equal((await run({ query: 'needle', sort: 'newest' })).results[0].session_id, 'history');
assert.equal((await run({ query: 'needle', scope: 'all', project: other })).results.length, 1);
assert.equal((await run({ query: 'needle', project: other })).results.length, 0);
await assert.rejects(run({ query: 'needle', limit: 11 }), /limit/);
await assert.rejects(run({ query: 'needle', detail: 'compact' }), /detail/);
await assert.rejects(run({ after: 'bad' }), /ISO/);
await assert.rejects(run({ query: 'x', session_id: 'history' }), /OR/);
const controller = new AbortController(); controller.abort();
await assert.rejects(searchSessions({}, ctx, controller.signal, root), { name: 'AbortError' });
const midflight = new AbortController();
const pending = searchSessions({}, ctx, midflight.signal, root);
setImmediate(() => midflight.abort());
await assert.rejects(pending, { name: 'AbortError' });
let registered;
(await jiti.import('../index.ts')).default({ registerTool: tool => { registered = tool; } });
assert.equal(registered.name, 'session_search');
console.log('Fixture behavior and tool registration passed.');
// Inspect existing sessions read-only, reporting counts only.
const realCtx = { cwd: join(temp, 'real-project'), sessionManager: { getSessionId: () => 'test-not-running', getSessionFile: () => undefined, getLeafId: () => null, getEntries: () => [], buildContextEntries: () => [] } };
const real = await searchSessions({ scope: 'all' }, realCtx);
assert(!JSON.stringify(real).includes('.jsonl'));
console.log(JSON.stringify({ real_session_count: real.total_sessions, warnings: real.warnings }));
